apiVersion: v1
kind: ConfigMap
metadata:
  name: group11-config
data:
  group: Group11
  image_url: |
    {  
       "failed_url": "https://group11finals.s3.amazonaws.com/failed.png"
      "success_url": "https://group11finals.s3.amazonaws.com/success.jpg", 
    }
